version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Docsaurus build.
          command: yarn build

      - run:
          name: Initialise Quant
          command: npm run quant -- init -c ${QUANT_CUSTOMER} -t '${QUANT_TOKEN}' --project=${QUANT_PROJECT} -e '${QUANT_ENDPOINT}' -d build

      - run:
          name: Check Quant config
          command: npm run quant -- info

      - save_cache:
          key: docs-{{ checksum "package-lock.json" }}
          paths:
            - build
            - node_modules

  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docs-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
